'use strict';
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
let motionOff=reduce.matches;
const motionButton=$('#motion-toggle');
function setMotion(off){motionOff=off;document.body.classList.toggle('motion-off',off);motionButton.setAttribute('aria-pressed',String(off));motionButton.textContent=off?'Включить анимацию':'Остановить анимацию';}
setMotion(motionOff);motionButton.addEventListener('click',()=>setMotion(!motionOff));reduce.addEventListener('change',e=>setMotion(e.matches));
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});$$('.reveal').forEach(el=>observer.observe(el));document.body.classList.add('js-ready');}
const menu=$('.menu-toggle');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню');$('#navigation').classList.toggle('open',open);});$$('#navigation a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');$('#navigation').classList.remove('open');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.setAttribute('aria-expanded','false');$('#navigation').classList.remove('open');}});
let ticking=false;function updateScroll(){const max=document.documentElement.scrollHeight-innerHeight;$('.scroll-progress').style.transform=`scaleX(${max>0?scrollY/max:0})`;$('.mobile-contact').classList.toggle('shown',scrollY>500);ticking=false;}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(updateScroll);ticking=true;}},{passive:true});updateScroll();
const tabs={languages:{tag:'ЗНАКОМИМСЯ С ЯЗЫКАМИ',title:'Мир больше,<br>чем кажется',text:'Английский и арабский становятся частью знакомства с миром. Развиваем любознательность и интерес к новым словам.',symbols:['Aa','أ ب'],color:'#ececd9'},school:{tag:'ГОТОВИМСЯ К НОВОМУ ЭТАПУ',title:'С интересом<br>к новым знаниям',text:'Подготовка к школе — одно из направлений RAVDA. Узнайте у администратора, как устроены занятия для возраста вашего ребёнка.',symbols:['1 2','3'],color:'#f0ddd0'},creative:{tag:'ПРОБУЕМ И СОЗДАЁМ',title:'«Смотрите,<br>я могу сам!»',text:'Творим, исследуем, пробуем новое. Маленькие повседневные открытия помогают детям становиться самостоятельнее.',symbols:['Я','могу!'],color:'#e0e9d9'},nature:{tag:'УЧИМСЯ У МИРА ВОКРУГ',title:'За каждым поворотом —<br>новое открытие',text:'Знакомимся с природой, гуляем и проводим время вместе. Обычная прогулка превращается в маленькое большое приключение.',symbols:['мир','вокруг'],color:'#ede4bb'}};
function activateTab(btn){const data=tabs[btn.dataset.tab];$$('[role=tab]').forEach(t=>{const active=t===btn;t.setAttribute('aria-selected',active);t.tabIndex=active?0:-1;});$('#learning-panel').setAttribute('aria-labelledby',btn.id);$('#learning-panel').style.background=data.color;$('#learning-tag').textContent=data.tag;$('#learning-title').innerHTML=data.title;$('#learning-text').textContent=data.text;$$('.learning-symbol span').forEach((s,i)=>s.textContent=data.symbols[i]);}
$$('[role=tab]').forEach((t,i,all)=>{t.addEventListener('click',()=>activateTab(t));t.addEventListener('keydown',e=>{let n;if(e.key==='ArrowDown'||e.key==='ArrowRight')n=(i+1)%all.length;else if(e.key==='ArrowUp'||e.key==='ArrowLeft')n=(i-1+all.length)%all.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=all.length-1;if(n!==undefined){e.preventDefault();activateTab(all[n]);all[n].focus();}});});
const media=$('#media-dialog'),content=$('#media-content');let previousFocus;
function openDialog(dialog){previousFocus=document.activeElement;dialog.showModal();document.body.style.overflow='hidden';}
$$('[data-video]').forEach(b=>b.addEventListener('click',()=>{const v=document.createElement('video');v.src='assets/'+b.dataset.video;v.controls=true;v.playsInline=true;v.preload='metadata';v.setAttribute('aria-label',b.dataset.video==='choose.mp4'?'Пять важных вопросов при выборе детского сада':'Прогулка и пикник RAVDA');content.replaceChildren(v);$('#media-caption').textContent=b.dataset.video==='choose.mp4'?'Питание, воспитатели, занятия, адаптация и атмосфера — видео RAVDA':'Маленькие большие приключения — видео RAVDA';openDialog(media);v.play().catch(()=>{});}));
$$('[data-image]').forEach(b=>b.addEventListener('click',()=>{const img=new Image();img.src=b.dataset.image;img.alt=b.dataset.caption||'Материал RAVDA';content.replaceChildren(img);$('#media-caption').textContent=b.dataset.caption||'';openDialog(media);}));
$$('[data-max]').forEach(b=>b.addEventListener('click',()=>openDialog($('#max-dialog'))));
$$('dialog').forEach(d=>{$('.dialog-close',d).addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.addEventListener('close',()=>{const v=$('video',d);if(v){v.pause();v.removeAttribute('src');v.load();}if(d===media)content.replaceChildren();document.body.style.overflow='';previousFocus?.focus();});});
$('#copy-phone').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('+79286755408');$('#copy-status').textContent='Номер скопирован. Вставьте его в поиск MAX.';}catch{$('#max-number').focus();$('#max-number').select();$('#copy-status').textContent='Выделили номер — скопируйте его и вставьте в поиск MAX.';}});
$('#year').textContent=new Date().getFullYear();
